language: android
sudo: true

jdk:
  - oraclejdk8

android:
  components:
    # Those two lines allow us to use any build tools version.
    - tools
    - platform-tools

    - build-tools-23.0.3
    - android-15

before_install:
  - mkdir -p $HOME/.gradle/caches/
  - mkdir -p $HOME/.gradle/wrapper/


# Currently we need sudo to stop the services (otherwise we run out of memory)
# With sudo caching doesn't work => disabled it
#before_cache:
#  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
#
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true

env:
  # Only compile and build basic jars
  - TARGET="assemble"
  - TARGET=":jsettlers.main.android:build"

  # Run single test targets
  - TARGET=":jsettlers.logic:test:unitTest"
  - TARGET=":jsettlers.common:test:test"
  - TARGET=":jsettlers.network:test --info"
  - TARGET=":jsettlers.logic:test:aiDifficultiesIT"
  - TARGET=":jsettlers.logic:test:autoReplayIT"
  - TARGET=":jsettlers.logic:test:replayValidationIT"
    
  # Test release generation
  - TARGET="release"

script: GRADLE_OPTS='-Xmx600m -Dorg.gradle.jvmargs="-Xmx1500m"' ./gradlew $TARGET
